-- AlterTable
ALTER TABLE `usuarios` ADD COLUMN `rol` ENUM('ADMINISTRADOR', 'MEDICO', 'ENFERMERO', 'AUXILIAR_ENFERMERIA', 'RECEPCION_ADMISIONES', 'REGENTE_FARMACIA', 'AUXILIAR_FARMACIA', 'QUIMICO_FARMACEUTICO') NOT NULL DEFAULT 'AUXILIAR_FARMACIA';
